In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [3]:
## define the vocab size
voc_size = 10000

In [4]:
## one hot representation
one_hot_rep = [one_hot(words,voc_size)for words in sent]
one_hot_rep

[[7285, 2743, 2796, 7545],
 [7285, 2743, 2796, 5939],
 [7285, 9258, 2796, 2859],
 [3451, 9090, 2300, 9206, 2707],
 [3451, 9090, 2300, 9206, 700],
 [5712, 7285, 178, 2796, 8082],
 [2374, 7769, 202, 9206]]

In [5]:
## word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np

In [8]:
sent_len = 8
embedded_docs = pad_sequences(one_hot_rep,padding='pre',maxlen=sent_len)
print(embedded_docs)

[[   0    0    0    0 7285 2743 2796 7545]
 [   0    0    0    0 7285 2743 2796 5939]
 [   0    0    0    0 7285 9258 2796 2859]
 [   0    0    0 3451 9090 2300 9206 2707]
 [   0    0    0 3451 9090 2300 9206  700]
 [   0    0    0 5712 7285  178 2796 8082]
 [   0    0    0    0 2374 7769  202 9206]]


In [9]:
## feature representation
dim = 10

In [10]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_len))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 81ms/step


array([[[-0.04740195, -0.02427044, -0.02329451, -0.03550856,
         -0.04809861,  0.02048992,  0.04619071, -0.02299523,
         -0.04448333,  0.0462698 ],
        [-0.04740195, -0.02427044, -0.02329451, -0.03550856,
         -0.04809861,  0.02048992,  0.04619071, -0.02299523,
         -0.04448333,  0.0462698 ],
        [-0.04740195, -0.02427044, -0.02329451, -0.03550856,
         -0.04809861,  0.02048992,  0.04619071, -0.02299523,
         -0.04448333,  0.0462698 ],
        [-0.04740195, -0.02427044, -0.02329451, -0.03550856,
         -0.04809861,  0.02048992,  0.04619071, -0.02299523,
         -0.04448333,  0.0462698 ],
        [-0.02896436, -0.01024486, -0.02398594, -0.03328177,
         -0.02067637,  0.00185477, -0.03366639, -0.0437614 ,
         -0.04974411, -0.00947722],
        [ 0.01865809, -0.04752858, -0.00922517,  0.00871459,
          0.01375185,  0.00930033,  0.02915175, -0.01831627,
         -0.00183069, -0.02915078],
        [ 0.00054181, -0.03043377, -0.02006463, -0.0

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 7285, 2743, 2796, 7545])

In [14]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 42ms/step


array([[-0.04740195, -0.02427044, -0.02329451, -0.03550856, -0.04809861,
         0.02048992,  0.04619071, -0.02299523, -0.04448333,  0.0462698 ],
       [-0.04740195, -0.02427044, -0.02329451, -0.03550856, -0.04809861,
         0.02048992,  0.04619071, -0.02299523, -0.04448333,  0.0462698 ],
       [-0.04740195, -0.02427044, -0.02329451, -0.03550856, -0.04809861,
         0.02048992,  0.04619071, -0.02299523, -0.04448333,  0.0462698 ],
       [-0.04740195, -0.02427044, -0.02329451, -0.03550856, -0.04809861,
         0.02048992,  0.04619071, -0.02299523, -0.04448333,  0.0462698 ],
       [-0.02896436, -0.01024486, -0.02398594, -0.03328177, -0.02067637,
         0.00185477, -0.03366639, -0.0437614 , -0.04974411, -0.00947722],
       [ 0.01865809, -0.04752858, -0.00922517,  0.00871459,  0.01375185,
         0.00930033,  0.02915175, -0.01831627, -0.00183069, -0.02915078],
       [ 0.00054181, -0.03043377, -0.02006463, -0.04392106,  0.01009288,
        -0.04518111,  0.00406671,  0.04124757